server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/example
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
